ALTER SESSION SET CURRENT_SCHEMA=VCUBE;
CREATE SEQUENCE VCUBE.SQ_TBSYMODULE_CDSEQMODULE START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE VCUBE.SQ_TBLGSETTING_CDSEQLOSET START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE VCUBE.SQ_TBLGLEVELCONF_CDSEQLEVELCON START WITH 1 INCREMENT BY 1;

CREATE TABLE VCUBE.TB_SY_MODULE (
  CD_SEQ_MODULE INT NOT NULL ,
  TP_CORE INT   NOT NULL ,
  NM_MODULE VARCHAR(50)   NOT NULL ,
  TX_PACKAGE VARCHAR(100)   NOT NULL ,
  NM_CREATE_USER VARCHAR(15)   NOT NULL ,
  DT_CREATE DATE   NOT NULL ,
  NM_UPDATE_USER VARCHAR(15)   NOT NULL ,
  DT_UPDATE DATE   NOT NULL );

COMMENT ON COLUMN VCUBE.TB_SY_MODULE.CD_SEQ_MODULE IS 'Log Setting Sequence Code';
COMMENT ON COLUMN VCUBE.TB_SY_MODULE.TP_CORE IS 'Indicates whether the module is core: 0 - No; 1 -Yes';
COMMENT ON COLUMN VCUBE.TB_SY_MODULE.NM_MODULE IS 'Module Name';
COMMENT ON COLUMN VCUBE.TB_SY_MODULE.TX_PACKAGE IS 'Package';
COMMENT ON COLUMN VCUBE.TB_SY_MODULE.NM_CREATE_USER IS 'Name of the user who created the record';
COMMENT ON COLUMN VCUBE.TB_SY_MODULE.DT_CREATE IS 'Record creation date';
COMMENT ON COLUMN VCUBE.TB_SY_MODULE.NM_UPDATE_USER IS 'Name of the last user who changed the record';
COMMENT ON COLUMN VCUBE.TB_SY_MODULE.DT_UPDATE IS 'Date the record was last updated';

CREATE TABLE VCUBE.TB_LG_SETTING (
  CD_SEQ_LOGSET INT   NOT NULL ,
  QT_SIZESYSTEM INT   NOT NULL ,
  QT_SIZECUSTOM INT   NOT NULL ,
  QT_DELDAYS INT NOT NULL,
  NM_CREATE_USER VARCHAR(15)   NOT NULL ,
  DT_CREATE DATE   NOT NULL ,
  NM_UPDATE_USER VARCHAR(15)   NOT NULL ,
  DT_UPDATE DATE   NOT NULL);



COMMENT ON COLUMN VCUBE.TB_LG_SETTING.CD_SEQ_LOGSET IS 'Log Setting Sequence Code';
COMMENT ON COLUMN VCUBE.TB_LG_SETTING.QT_DELDAYS IS 'Number of days to purge the data in the database.';
COMMENT ON COLUMN VCUBE.TB_LG_SETTING.QT_SIZESYSTEM IS 'size of the system log file in MB';
COMMENT ON COLUMN VCUBE.TB_LG_SETTING.QT_SIZECUSTOM IS 'size of the system log file in MB';
COMMENT ON COLUMN VCUBE.TB_LG_SETTING.NM_CREATE_USER IS 'Name of the user who created the record';
COMMENT ON COLUMN VCUBE.TB_LG_SETTING.DT_CREATE IS 'Record creation date';
COMMENT ON COLUMN VCUBE.TB_LG_SETTING.NM_UPDATE_USER IS 'Name of the last user who changed the record';
COMMENT ON COLUMN VCUBE.TB_LG_SETTING.DT_UPDATE IS 'Date the record was last updated';

CREATE SEQUENCE VCUBE.SQ_TBLGRECORD_CDSEQLOGREC START WITH 1 INCREMENT BY 1;

CREATE TABLE VCUBE.TB_LG_RECORD (
  CD_SEQ_LOGREC INT DEFAULT SQ_TBLGRECORD_CDSEQLOGREC.NEXTVAL  NOT NULL ,
  CD_SEQ_MODULE INT   NOT NULL ,
  DT_LOG DATE   NOT NULL ,
  TP_LOG INT   NOT NULL ,
  NM_USER VARCHAR(15)    ,
  TX_REMOTEIP VARCHAR(15)    ,
  TP_LEVEL INT    ,
  TX_MESSAGE VARCHAR(100)    ,
  TX_LOG BLOB    ,
  NM_CREATE_USER VARCHAR(15)   NOT NULL ,
  DT_CREATE DATE   NOT NULL ,
  NM_UPDATE_USER VARCHAR(15)   NOT NULL ,
  DT_UPDATE DATE   NOT NULL);

ALTER TABLE VCUBE.TB_LG_RECORD ADD CONSTRAINT
PK_TBLGRECORD PRIMARY KEY (CD_SEQ_LOGREC);

CREATE INDEX VCUBE.IN_FKLGRECORD_CDMODULE ON TB_LG_RECORD (CD_SEQ_MODULE);

COMMENT ON COLUMN VCUBE.TB_LG_RECORD.CD_SEQ_LOGREC IS 'Log Setting Sequence Code';
COMMENT ON COLUMN VCUBE.TB_LG_RECORD.DT_LOG IS 'size of the system log file in MB';
COMMENT ON COLUMN VCUBE.TB_LG_RECORD.TP_LOG IS 'Log Type: 1 - System; 2 - Custom';
COMMENT ON COLUMN VCUBE.TB_LG_RECORD.NM_USER IS 'User Name';
COMMENT ON COLUMN VCUBE.TB_LG_RECORD.TX_REMOTEIP IS 'Remote IP Address';
COMMENT ON COLUMN VCUBE.TB_LG_RECORD.TX_MESSAGE IS 'Summary log';
COMMENT ON COLUMN VCUBE.TB_LG_RECORD.TX_LOG IS 'Detailed log';
COMMENT ON COLUMN VCUBE.TB_LG_RECORD.NM_CREATE_USER IS 'Name of the user who created the record';
COMMENT ON COLUMN VCUBE.TB_LG_RECORD.DT_CREATE IS 'Record creation date';
COMMENT ON COLUMN VCUBE.TB_LG_RECORD.NM_UPDATE_USER IS 'Name of the last user who changed the record';
COMMENT ON COLUMN VCUBE.TB_LG_RECORD.DT_UPDATE IS 'Date the record was last updated';


CREATE TABLE VCUBE.TB_LG_LEVELCONF (
  CD_SEQ_LEVELCONF INT  NOT NULL ,
  CD_SEQ_LOGSET INT   NOT NULL ,
  CD_SEQ_MODULE INT   NOT NULL ,
  TX_APPENDER VARCHAR(50)    ,
  TP_LEVEL INT   NOT NULL ,
  NM_CREATE_USER VARCHAR(15)   NOT NULL ,
  DT_CREATE DATE   NOT NULL ,
  NM_UPDATE_USER VARCHAR(15)   NOT NULL ,
  DT_UPDATE DATE   NOT NULL);


COMMENT ON COLUMN VCUBE.TB_LG_LEVELCONF.CD_SEQ_LEVELCONF IS 'Log Setting Sequence Code';
COMMENT ON COLUMN VCUBE.TB_LG_LEVELCONF.CD_SEQ_MODULE IS 'Module code';
COMMENT ON COLUMN VCUBE.TB_LG_LEVELCONF.TX_APPENDER IS 'Appender file';
COMMENT ON COLUMN VCUBE.TB_LG_LEVELCONF.TP_LEVEL IS 'level of details of the system log file: 0 - Off - No Logs; 1 - Fatal; 2 - Error; 3 - Info; 4 - Warn; 5 - Debug; 6 - Trace; 7 - All - All logs ';
COMMENT ON COLUMN VCUBE.TB_LG_LEVELCONF.NM_CREATE_USER IS 'Name of the user who created the record';
COMMENT ON COLUMN VCUBE.TB_LG_LEVELCONF.DT_CREATE IS 'Record creation date';
COMMENT ON COLUMN VCUBE.TB_LG_LEVELCONF.NM_UPDATE_USER IS 'Name of the last user who changed the record';
COMMENT ON COLUMN VCUBE.TB_LG_LEVELCONF.DT_UPDATE IS 'Date the record was last updated';

CREATE INDEX VCUBE.IFK_FK_SYMODULE_LGLEVELCONF ON TB_LG_LEVELCONF (CD_SEQ_MODULE);
CREATE INDEX VCUBE.IFK_FK_LGSETTING_LGLEVELCONF ON TB_LG_LEVELCONF (CD_SEQ_LOGSET);

ALTER TABLE VCUBE.TB_SY_MODULE ADD CONSTRAINT
CC_TBSYMODULE_CDSEQMODULE CHECK (TP_CORE IN (0,1));

ALTER TABLE VCUBE.TB_SY_MODULE ADD CONSTRAINT
PK_TBSYMODULE PRIMARY KEY (CD_SEQ_MODULE);

ALTER TABLE VCUBE.TB_LG_SETTING ADD CONSTRAINT
PK_TBLGSETTING PRIMARY KEY (CD_SEQ_LOGSET);

ALTER TABLE VCUBE.TB_LG_LEVELCONF ADD CONSTRAINT
PK_TBLGLEVELCONF PRIMARY KEY (CD_SEQ_LEVELCONF);

ALTER TABLE VCUBE.TB_LG_LEVELCONF ADD CONSTRAINT
FK_TBSYMODULE_TBLGLEVELCONF FOREIGN KEY (CD_SEQ_MODULE)
REFERENCES VCUBE.TB_SY_MODULE(CD_SEQ_MODULE);

ALTER TABLE VCUBE.TB_LG_LEVELCONF ADD CONSTRAINT
FK_TB_LG_SETTING_TBLGLEVELCONF FOREIGN KEY (CD_SEQ_LOGSET)
REFERENCES VCUBE.TB_LG_SETTING(CD_SEQ_LOGSET);

ALTER TABLE VCUBE.TB_LG_LEVELCONF ADD CONSTRAINT
CC_TBLGLEVELCONF_TPLEVEL CHECK (TP_LEVEL IN (0,1,2,3,4,5,6,7));

ALTER TABLE VCUBE.TB_LG_RECORD ADD CONSTRAINT 
FK_TBSYMODULE_TBLGRECORD FOREIGN KEY (CD_SEQ_MODULE)
REFERENCES TB_SY_MODULE(CD_SEQ_MODULE);


