INSERT INTO VCUBE.TB_SY_MODULE
(CD_SEQ_MODULE, TP_CORE, NM_MODULE, TX_PACKAGE, NM_CREATE_USER, DT_CREATE, NM_UPDATE_USER, DT_UPDATE)
VALUES("VCUBE"."SQ_TBSYMODULE_CDSEQMODULE"."NEXTVAL", 0, 'spring-boot', 'org.springframework.boot', 'geovannyribeiro', sysdate, 'geovannyribeiro', sysdate);

INSERT INTO VCUBE.TB_LG_SETTING
(CD_SEQ_LOGSET, QT_SIZESYSTEM, QT_SIZECUSTOM, QT_DELDAYS, NM_CREATE_USER, DT_CREATE, NM_UPDATE_USER, DT_UPDATE)
VALUES("VCUBE"."SQ_TBLGSETTING_CDSEQLOSET"."NEXTVAL", 0, 0, 0, 'geovannyribeiro', sysdate, 'geovannyribeiro', sysdate);

INSERT INTO VCUBE.TB_LG_LEVELCONF
(CD_SEQ_LEVELCONF, CD_SEQ_LOGSET, CD_SEQ_MODULE, TX_APPENDER, TP_LEVEL, NM_CREATE_USER, DT_CREATE, NM_UPDATE_USER, DT_UPDATE)
VALUES("VCUBE"."SQ_TBLGLEVELCONF_CDSEQLEVELCON"."NEXTVAL", 1, 1, 'vcubeAppender', 6, 'geovannyribeiro', sysdate, 'geovannyribeiro', sysdate);



INSERT INTO VCUBE.TB_SY_MODULE
(CD_SEQ_MODULE, TP_CORE, NM_MODULE, TX_PACKAGE, NM_CREATE_USER, DT_CREATE, NM_UPDATE_USER, DT_UPDATE)
VALUES("VCUBE"."SQ_TBSYMODULE_CDSEQMODULE"."NEXTVAL", 0, 'v3-view', 'com.vmetrix.v3.cloud.view.main', 'geovannyribeiro', sysdate, 'geovannyribeiro', sysdate);

INSERT INTO VCUBE.TB_LG_SETTING
(CD_SEQ_LOGSET, QT_SIZESYSTEM, QT_SIZECUSTOM, QT_DELDAYS, NM_CREATE_USER, DT_CREATE, NM_UPDATE_USER, DT_UPDATE)
VALUES("VCUBE"."SQ_TBLGSETTING_CDSEQLOSET"."NEXTVAL", 0, 0, 0, 'geovannyribeiro', sysdate, 'geovannyribeiro', sysdate);


INSERT INTO VCUBE.TB_LG_LEVELCONF
(CD_SEQ_LEVELCONF, CD_SEQ_LOGSET, CD_SEQ_MODULE, TX_APPENDER, TP_LEVEL, NM_CREATE_USER, DT_CREATE, NM_UPDATE_USER, DT_UPDATE)
VALUES("VCUBE"."SQ_TBLGLEVELCONF_CDSEQLEVELCON"."NEXTVAL", 2, 2, 'vcubeAppender,v3DatabaseAppender', 4, 'geovannyribeiro', sysdate, 'geovannyribeiro', sysdate);




INSERT INTO VCUBE.TB_LG_LEVELCONF
(CD_SEQ_LEVELCONF, CD_SEQ_LOGSET, CD_SEQ_MODULE, TX_APPENDER, TP_LEVEL, NM_CREATE_USER, DT_CREATE, NM_UPDATE_USER, DT_UPDATE)
VALUES("VCUBE"."SQ_TBLGLEVELCONF_CDSEQLEVELCON"."NEXTVAL", 2, 2, 'v3DatabaseAppender', 4, 'geovannyribeiro', sysdate, 'geovannyribeiro', sysdate);

INSERT INTO VCUBE.TB_SY_MODULE
(CD_SEQ_MODULE, TP_CORE, NM_MODULE, TX_PACKAGE, NM_CREATE_USER, DT_CREATE, NM_UPDATE_USER, DT_UPDATE)
VALUES(3, 0, 'v3-logs-test', 'com.vmetrix.v3.logsmanangement.api', 'geovannyribeiro', TIMESTAMP '2022-04-12 15:53:57.000000', 'geovannyribeiro', TIMESTAMP '2022-04-12 15:53:57.000000');

INSERT INTO VCUBE.TB_LG_LEVELCONF
(CD_SEQ_LEVELCONF, CD_SEQ_LOGSET, CD_SEQ_MODULE, TX_APPENDER, TP_LEVEL, NM_CREATE_USER, DT_CREATE, NM_UPDATE_USER, DT_UPDATE)
VALUES(7, 2, 3, 'vcubeAppender,v3DatabaseAppender', 4, 'geovannyribeiro', TIMESTAMP '2022-04-12 15:55:06.000000', 'geovannyribeiro', TIMESTAMP '2022-04-12 15:55:06.000000');


INSERT INTO VCUBE.TB_LG_SETTING
(CD_SEQ_LOGSET, QT_SIZESYSTEM, QT_SIZECUSTOM, QT_DELDAYS, NM_CREATE_USER, DT_CREATE, NM_UPDATE_USER, DT_UPDATE)
VALUES(3, 0, 0, 0, 'geovannyribeiro', TIMESTAMP '2022-04-12 18:11:07.000000', 'geovannyribeiro', TIMESTAMP '2022-04-12 18:11:07.000000');